# Generated by Django 6.0.7 on 2026-08-04 15:24

from django.db import migrations


def create_public_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Domain = apps.get_model("tenants", "Domain")

    tenant, _ = Tenant.objects.get_or_create(
        schema_name="public",
        defaults={"name": "Public", "slug": "public"},
    )

    for domain_name in ["localhost", "127.0.0.1"]:
        Domain.objects.get_or_create(
            domain=domain_name,
            defaults={"tenant": tenant, "is_primary": domain_name == "localhost"},
        )


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_public_tenant, reverse),
    ]