# Generated by Django 6.0.7 on 2026-08-17 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone number'),
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_users',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='\n        Target email address associated with the token.\n        ', max_length=254)),
                ('token_hash', models.CharField(db_index=True, help_text='\n        SHA256 hash of the raw token.\n\n        Raw token is never stored.\n        ', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='\n        Arbitrary token-specific data.\n\n        Examples:\n\n        Invitation:\n            {\n                "company_id": 1\n            }\n\n        Change email:\n            {\n                "new_email": "new@test.com"\n            }\n        ')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='\n        Token expiration timestamp.\n        ')),
                ('used_at', models.DateTimeField(blank=True, help_text='\n        Set once token is consumed.\n\n        Prevents token reuse.\n        ', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='\n        Token manually revoked before expiration.\n        ', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='\n        Soft-delete timestamp.\n        ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='\n        Optional user linked to the token.\n\n        Invitation tokens may exist before a user account\n        has been created.\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_tokens',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email'], name='auth_tokens_email_01defd_idx'), models.Index(fields=['expires_at'], name='auth_tokens_expires_f09206_idx'), models.Index(fields=['token_hash'], name='auth_tokens_token_h_a265e8_idx')],
            },
        ),
    ]
