# Generated by Django 6.0.7 on 2026-08-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('identification_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tenants.tenant')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='companies_name_idx'), models.Index(fields=['is_verified'], name='companies_verified_idx'), models.Index(fields=['deleted_at'], name='companies_deleted_idx'), models.Index(fields=['created_at'], name='companies_created_idx'), models.Index(fields=['identification_number'], name='companies_ident_num_idx')],
            },
        ),
    ]
