# Generated by Django 6.0.7 on 2026-08-19 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_populate_company_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
